export type Lang = 'en' | 'bn';

export const translations = {
  en: {
    waitingTitle: 'Affiliate Account Under Review',
    waitingMessage: 'Your affiliate account is under review. Admin will approve your affiliate account within 24–48 hours.',
    contactAdmin: 'Contact Admin',
    backToHome: '← Back to Home',
    fullName: 'Full Name',
    email: 'Email',
    telegram: 'Telegram (optional)',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    promotionMethod: 'How do you sell our services?',
    promotionPlaceholder: 'Facebook Marketing, Telegram Promotion, YouTube, TikTok, Paid Ads, SEO, Personal Network...',
    register: 'Create Account',
    registering: 'Creating...',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    becomeAffiliate: 'Become an Affiliate',
    earnCommission: 'Earn 20% commission on every sale',
    alreadyAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    signInHere: 'Sign in',
    backToHomeBtn: '← Back to Home',
    whatYouGet: 'What you get:',
    feature1: 'Unique referral link',
    feature2: '5% discount coupon for buyers',
    feature3: '20% commission on sales',
    feature4: 'Real-time analytics dashboard',
    minChars: 'Min 6 characters',
    repeatPassword: 'Repeat password',
    welcomeBack: 'Welcome back!',
    accountCreated: 'Account created! Welcome to the affiliate program.',
    pendingSuccess: 'Registration successful! Your account is pending approval.',
    language: 'Language',
    english: 'English',
    bangla: 'বাংলা',
    dashboard: 'Dashboard',
    wallet: 'Wallet',
    referrals: 'Referrals',
    withdrawals: 'Withdrawals',
    coupons: 'Coupons',
    settings: 'Settings',
    logout: 'Logout',
    pendingStatus: 'Pending',
    approvedStatus: 'Approved',
    rejectedStatus: 'Rejected',
    bannedStatus: 'Banned',
  },
  bn: {
    waitingTitle: 'আপনার অ্যাফিলিয়েট একাউন্ট রিভিউতে রয়েছে',
    waitingMessage: 'আপনার অ্যাফিলিয়েট একাউন্ট রিভিউতে রয়েছে। অ্যাডমিন ২৪–৪৮ ঘণ্টার মধ্যে আপনার একাউন্ট অনুমোদন করবে।',
    contactAdmin: 'অ্যাডমিনের সাথে যোগাযোগ করুন',
    backToHome: '← হোমপেজে ফিরুন',
    fullName: 'পূর্ণ নাম',
    email: 'ইমেইল',
    telegram: 'টেলিগ্রাম (ঐচ্ছিক)',
    password: 'পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    promotionMethod: 'আপনি কীভাবে আমাদের সেবা বিক্রি করেন?',
    promotionPlaceholder: 'ফেসবুক মার্কেটিং, টেলিগ্রাম প্রমোশন, ইউটিউব, টিকটক, পেইড এডস, এসইও, ব্যক্তিগত নেটওয়ার্ক...',
    register: 'একাউন্ট তৈরি করুন',
    registering: 'তৈরি হচ্ছে...',
    signIn: 'সাইন ইন',
    signingIn: 'সাইন ইন হচ্ছে...',
    becomeAffiliate: 'অ্যাফিলিয়েট হোন',
    earnCommission: 'প্রতি বিক্রয়ে ২০% কমিশন উপার্জন করুন',
    alreadyAccount: 'ইতিমধ্যে একাউন্ট আছে?',
    noAccount: 'একাউন্ট নেই?',
    registerHere: 'এখানে রেজিস্টার করুন',
    signInHere: 'সাইন ইন করুন',
    backToHomeBtn: '← হোমপেজে ফিরুন',
    whatYouGet: 'আপনি যা পাচ্ছেন:',
    feature1: 'ইউনিক রেফারেল লিংক',
    feature2: 'ক্রেতাদের জন্য ৫% ডিসকাউন্ট কুপন',
    feature3: 'বিক্রয়ে ২০% কমিশন',
    feature4: 'রিয়েল-টাইম অ্যানালিটিক্স ড্যাশবোর্ড',
    minChars: 'সর্বনিম্ন ৬ অক্ষর',
    repeatPassword: 'পাসওয়ার্ড পুনরায় লিখুন',
    welcomeBack: 'স্বাগতম!',
    accountCreated: 'একাউন্ট তৈরি হয়েছে! অ্যাফিলিয়েট প্রোগ্রামে স্বাগতম।',
    pendingSuccess: 'রেজিস্ট্রেশন সফল! আপনার একাউন্ট অনুমোদনের অপেক্ষায় রয়েছে।',
    language: 'ভাষা',
    english: 'English',
    bangla: 'বাংলা',
    dashboard: 'ড্যাশবোর্ড',
    wallet: 'ওয়ালেট',
    referrals: 'রেফারেল',
    withdrawals: 'উইথড্র',
    coupons: 'কুপন',
    settings: 'সেটিংস',
    logout: 'লগআউট',
    pendingStatus: 'অপেক্ষমান',
    approvedStatus: 'অনুমোদিত',
    rejectedStatus: 'প্রত্যাখ্যাত',
    bannedStatus: 'নিষিদ্ধ',
  },
};

export type TranslationKey = keyof typeof translations.en;
